### ISSUE TITLE
Any chance of installation instructions for non-programmers?

### ISSUE THREAD

**Issue by Necrodude** [djdembeck/Audnexus.bundle#46]
Any chance of installation instructions for non-programmers?

**Comment by djdembeck** [comment]
They already are for general public. You’ll need to be more specific

**Comment by Necrodude** [comment]
Me be more specific? lol

Well, you recommend what I assume is an app called Git. No link, but I did a Google search and found something. Then, for some odd reason, I have to copy and paste a line into this Git which tells me it extracted some files but it didn't magically find my Plex directory and didn't add anything into my plugins folder. So I installed it manually and renamed the folder by removing "-master". Restart. No Audnexus in the dropdown. Deleted it.  Found where Git created this plugin and used that one instead. Restart. No Audnexus in the dropdown. 

I'm a pretty independent guy who is always happy to Google search and go down the rabbit hole to figure things out for myself. But I didn't understand a single thing in your instructions and had to look at wikis and several searches to figure it out. And it still didn't work.

**Comment by qgiguiere** [comment]
Git is a very common program, its generally assumed you know what it is at least if you are here. You are literally on a site called github after all. The reason there is no link to git is because how to install it depends on what operating system you are using. Other than that, the instructions are very clear and straightforward. I suggest reading them carefully and following them step by step. He even provides links to plex documentation to know where to install the plug-in. It's actually very simple if you just do what is outlined in the instructions. Next time if you have an issue, be specific about what problem you are having and what you have already done to try to solve it instead of just a vague request.

**Comment by seanap** [comment]
@Necrodude would these steps help to understand what to do better? https://github.com/seanap/Audiobooks.bundle#installation

The steps outlined above are for a more manual installation method, which works, but may get annoying if you need to do all those steps every time you upgrade the plugin.  To save me a lot of time when upgrading I wrote a simple update script that uses git as outlined in the install section on this repo https://pastebin.com/L4cFw39A

**Comment by Necrodude** [comment]
Perfect.

**Comment by Necrodude** [comment]
> Git is a very common program, its generally assumed you know what it is at least if you are here. You are literally on a site called github after all. The reason there is no link to git is because how to install it depends on what operating system you are using. Other than that, the instructions are very clear and straightforward. I suggest reading them carefully and following them step by step. He even provides links to plex documentation to know where to install the plug-in. It's actually very simple if you just do what is outlined in the instructions. Next time if you have an issue, be specific about what problem you are having and what you have already done to try to solve it instead of just a vague request.

I solved my own problem. I just suggested a more user-friendly set of instructions.
