### ISSUE TITLE
Duplicate albums in Plex for each file

### ISSUE THREAD

**Issue by Nelluk** [djdembeck/Audnexus.bundle#63]
The first two books I added to my library worked as expected. The third is giving me a distinct album for each of the files, even though the Artist and Album Artist are tagged consistently. I'm sure this is user error but I'm out of ideas.

[Screenshot of Plex appearance](https://i.imgur.com/ib30fzf.png)

[Screenshot of tags in mp3tag](https://i.imgur.com/9W4IEbE.png)

**Comment by plmcgrn** [comment]
It's likely due to the multiple files.  Plex doesn't always handle that well.  If you select them all, you should be able to merge them into one entry.

Sent while mobile. Excuse typos.
________________________________
From: Nelluk ***@***.***>
Sent: Tuesday, September 20, 2022 8:33:41 PM
To: djdembeck/Audnexus.bundle ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [djdembeck/Audnexus.bundle] Duplicate albums in Plex for each file (Issue #63)


The first two books I added to my library worked as expected. The third is giving me a distinct album for each of the files, even though the Artist and Album Artist are names consistently. I'm sure this is user error but I'm out of ideas.

Screenshot of Plex appearance<https://i.imgur.com/ib30fzf.png>

Screenshot of tags in mp3tag<https://i.imgur.com/9W4IEbE.png>
